apiVersion: v1
data:
  mapRoles: |
    - groups:
      - system:bootstrappers
      - system:nodes
      rolearn: arn:aws:iam::057006087726:role/eksctl-frank-jwt-api-nodegroup-ng--NodeInstanceRole-eHdnXNmBUdzh
      username: system:node:{{EC2PrivateDNSName}}
    - groups:
      - system:masters
      rolearn: arn:aws:iam::057006087726:role/UdacityFlaskDeployCBKubectlRole
      username: build   
kind: ConfigMap
metadata:
  creationTimestamp: "2025-01-17T16:52:18Z"
  name: aws-auth
  namespace: kube-system
  resourceVersion: "1208"
  uid: 9afba6b8-89e6-4eae-a354-a48f2a1c3e09
